# Immagini Docker
controller[image]="kathara/pox"
s1[image]="kathara/sdn"
s2[image]="kathara/sdn"
l1[image]="kathara/sdn"
l2[image]="kathara/sdn"
l3[image]="kathara/sdn"
w1[image]="kathara/base"
w2[image]="kathara/base"
w3[image]="kathara/base"
w4[image]="kathara/base"
c1[image]="kathara/base"

# Rete di Management (Control Plane) su eth0
controller[0]="M"
s1[0]="M"
s2[0]="M"
l1[0]="M"
l2[0]="M"
l3[0]="M"

# Data Plane: Collegamenti Spine-Leaf
# S1 connesso a L1, L2, L3
s1[1]="A"
l1[1]="A"
s1[2]="B"
l2[1]="B"
s1[3]="C"
l3[1]="C"

# S2 connesso a L1, L2, L3
s2[1]="D"
l1[2]="D"
s2[2]="E"
l2[2]="E"
s2[3]="F"
l3[2]="F"

# Data Plane: Collegamenti Leaf-Hosts
# L1 a W1 e W2
l1[3]="W1"
w1[0]="W1"
l1[4]="W2"
w2[0]="W2"

# L2 a W3 e W4
l2[3]="W3"
w3[0]="W3"
l2[4]="W4"
w4[0]="W4"

# L3 a C1 (Collector)
l3[3]="C1"
c1[0]="C1"